# Generated by Django 2.2.6 on 2021-07-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_titles_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
    ]
