# Generated by Django 2.2.6 on 2021-07-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_titles_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
