# Generated by Django 2.2.6 on 2021-07-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210716_2351'),
        ('api', '0002_auto_20210716_1337'),
    ]

    operations = [
    ]
