# Generated by Django 2.2.6 on 2021-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20210717_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USR', 'user'), ('ADM', 'admin'), ('MOD', 'moderator')], default='USR', max_length=3),
        ),
    ]
