# Generated by Django 2.2.6 on 2021-07-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210719_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
